version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
build_script:
- ps: >-
    nuget restore

    msbuild ModHelper /p:Configuration=Release /p:Platform=AnyCPU /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild ModLoader /p:Configuration=Release /p:Platform=AnyCPU /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild Proxy /p:Configuration=Release /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
- ps: >-
    New-Item -Path build\${env:CONFIGURATION}\Mods -Type Directory

    New-Item -Path build\dist\Mods -Type Directory

    Copy-Item ModConfig.ini -Destination build\${env:CONFIGURATION}

    Copy-Item ModConfig.ini -Destination build\dist

    Copy-Item build\${env:CONFIGURATION}\*.dll -Destination build\dist

    Copy-Item build\${env:CONFIGURATION}\Mods\*.dll -Destination build\dist\Mods

artifacts:
- path: build\$(configuration)
  name: With PDB

- path: build\dist
  name: Release
